# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 022299d7f5fdb1792f329ebe34574e16b40c7845819f9a3d81caa1f10bd5ce999ced2dad35eb46e6b0c72d1c55c60bec05302758285694faa035b506b1b0544e

test:
  secret_key_base: 53bb0f2452f49d5e71c715fa892fff4d3cf0fd2cbf58ab7e7c5b6b296841ed578ec118d4212a5706719b3bdcfaa307d3bdfa8f014a5bbdb9677222c9c69c6901

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
